/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 79a596070ced0aa2dd4a1c366bc4f5b7)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	IMAGES: ImagesBinding;
	PURGE_ENABLED: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PURGE_ENABLED">> {}
}
